# Use root/example user/password credentials

version: '3.1'

services:
    www:
        build:
          context: .
          dockerfile: Dockerfile
        ports: 
            - "8090:8080"
        volumes:
            - ./src:/var/www/localhost/htdocs
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: dbpass 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8089:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: dbpass
            MYSQL_ROOT_PASSWORD: dbpass 
volumes:
    persistent:
